; [yugabyte]
; 35.188.87.216 ansible_user=packer



[all]
node1 master_ip=34.27.219.223 cloud_location=gcp.us-central1.a ansible_user=packer
node2 ansible_host=34.58.200.145 cloud_location=gcp.us-central1.b ansible_user=packer
node3 ansible_host=35.223.251.65 cloud_location=gcp.us-central1.c ansible_user=packer
node4 ansible_host=34.58.200.145 ansible_user=packer

[all:vars]

yugabyte_path=/home/packer/yugabyte-2.25.0.0
base_dir=/home/packer/

